// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUiSqpGfLLcSksVe8N7A68yPu8W4SA2Eo',
    appId: '1:562010341880:web:48ae00c848ec585a52160d',
    messagingSenderId: '562010341880',
    projectId: 'tiktokclone-3260b',
    authDomain: 'tiktokclone-3260b.firebaseapp.com',
    storageBucket: 'tiktokclone-3260b.appspot.com',
    measurementId: 'G-GERHGQDRKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRhoyRBl08L9JsfoSV-zV_h9_FftBWigw',
    appId: '1:562010341880:android:3b14a9e74190b8aa52160d',
    messagingSenderId: '562010341880',
    projectId: 'tiktokclone-3260b',
    storageBucket: 'tiktokclone-3260b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB44-FEUtbPXpRBWJyhMq0od2YzGL2sQHQ',
    appId: '1:562010341880:ios:a7bb709a9082937452160d',
    messagingSenderId: '562010341880',
    projectId: 'tiktokclone-3260b',
    storageBucket: 'tiktokclone-3260b.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );

}